### ISSUE TITLE
Warrior Suggestions

### ISSUE THREAD

**Issue by FactoDoesStuff** [McWars/Reporter#2]
- Remove the /freeze command and implement it into the StaffCore repo. 

- Add some pvp-related commands, like /challenge {USERNAME} to challenge them to a 1v1. Or maybe even /queue to open a menu up to click either 1v1, 2v2, or 3v3.

**Comment by realjbtytm** [comment]
Will add.

**Comment by realjbtytm** [comment]
Removed freeze command due to glitch.
