### ISSUE TITLE
StaffCore Suggestions

### ISSUE THREAD

**Issue by FactoDoesStuff** [McWars/Reporter#4]
- Maybe for the punishments, it can send a tellraw message to the users of the server announcing that a player was punished from the server that will include the type of punishment and the duration of it, along with the reason the moderator gave the punishment.

**Comment by realjbtytm** [comment]
No need for the tellraw due to the fact that we are now using Skript for our plugins now.

**Comment by realjbtytm** [comment]
However, we are planning to do that.
